spring:
  application:
    name: 04-irctc-booking

  config:
    import: "configserver:http://localhost:8888"

  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/class_practice
    username: root
    password: Root123@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

    register-with-eureka: true
    fetch-registry: true